# --------------------------------------------------------------------------------
# Name:     Config.yml
# Purpose:  1) As the side panel in GitHub pages
#           2) To set up the Styles in the page
#
# Author:   Man-Kong Wong
#
# Version:  1.00    
# Created:  2024-03-04
#
# --------------------------------------------------------------------------------

# Basic site settings
locale : "en-US"                       # Language setting
title : "Portfolio"                    # Site title
repository : "michael-mkw/michael-mkw.github.io"
url : https://michael-mkw.github.io


# Sidebar settings
author:
  avatar : "https://github.com/michael-mkw/michael-mkw.github.io/blob/main/images/GitHubProfilePicCircle.png"
  name : "Michael Wong"
  bio : "GIS Analyst | Surveyor"


theme : "jekyll-theme-minimal"         # Page theme
